export const CREATE_QUOTATION_REQUEST = 'CREATE_QUOTATION_REQUEST';
export const CREATE_QUOTATION_SUCCESS = 'CREATE_QUOTATION_SUCCESS';
export const CREATE_QUOTATION_FAILURE = 'CREATE_QUOTATION_FAILURE';

export const EDIT_QUOTATION_REQUEST = 'EDIT_QUOTATION_REQUEST';
export const EDIT_QUOTATION_SUCCESS = 'EDIT_QUOTATION_SUCCESS';
export const EDIT_QUOTATION_FAILURE = 'EDIT_QUOTATION_FAILURE';

export const DELETE_QUOTATION_REQUEST = 'DELETE_QUOTATION_REQUEST';
export const DELETE_QUOTATION_SUCCESS = 'DELETE_QUOTATION_SUCCESS';
export const DELETE_QUOTATION_FAILURE = 'DELETE_QUOTATION_FAILURE';

export const LIKE_QUOTATION_REQUEST = 'LIKE_QUOTATION_REQUEST';
export const LIKE_QUOTATION_SUCCESS = 'LIKE_QUOTATION_SUCCESS';
export const LIKE_QUOTATION_FAILURE = 'LIKE_QUOTATION_FAILURE';

export const DISLIKE_QUOTATION_REQUEST = 'DISLIKE_QUOTATION_REQUEST';
export const DISLIKE_QUOTATION_SUCCESS = 'DISLIKE_QUOTATION_SUCCESS';
export const DISLIKE_QUOTATION_FAILURE = 'DISLIKE_QUOTATION_FAILURE';

export const SORT_QUOTES_REQUEST = 'SORT_QUOTES_REQUEST';
export const SORT_QUOTES_SUCCESS = 'SORT_QUOTES_SUCCESS';
export const SORT_QUOTES_FAILURE = 'SORT_QUOTES_FAILURE';

export const FILTER_QUOTES_REQUEST = 'FILTER_QUOTES_REQUEST';
export const FILTER_QUOTES_SUCCESS = 'FILTER_QUOTES_SUCCESS';
export const FILTER_QUOTES_FAILURE = 'FILTER_QUOTES_FAILURE';

export const LOAD_MORE_QUOTES_REQUEST = 'LOAD_MORE_QUOTES_REQUEST';
export const LOAD_MORE_QUOTES_SUCCESS = 'LOAD_MORE_QUOTES_SUCCESS';
export const LOAD_MORE_QUOTES_FAILURE = 'LOAD_MORE_QUOTES_FAILURE';

export const RESET_PAGINATION = 'RESET_PAGINATION';
export const RESET_QUOTES_STATE = 'RESET_QUOTES_STATE';
